// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD838Hg9nOQtoN-mgCMzSnXzJjAjA1AC5k',
    appId: '1:928429831821:web:9eb7321323b3c1975d54c4',
    messagingSenderId: '928429831821',
    projectId: 'flexshow-5c47c',
    authDomain: 'flexshow-5c47c.firebaseapp.com',
    storageBucket: 'flexshow-5c47c.appspot.com',
    measurementId: 'G-ZWGC2KHJ7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp9QqC58sRKFDMZbps6WbS9bCav6hoV0E',
    appId: '1:928429831821:android:ba15d899293479415d54c4',
    messagingSenderId: '928429831821',
    projectId: 'flexshow-5c47c',
    storageBucket: 'flexshow-5c47c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEq0UqDMLRJYZb9-QTXul_ARINMp-lcKk',
    appId: '1:928429831821:ios:dba9511e64e6f40c5d54c4',
    messagingSenderId: '928429831821',
    projectId: 'flexshow-5c47c',
    storageBucket: 'flexshow-5c47c.appspot.com',
    iosBundleId: 'com.example.flexshow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEq0UqDMLRJYZb9-QTXul_ARINMp-lcKk',
    appId: '1:928429831821:ios:dba9511e64e6f40c5d54c4',
    messagingSenderId: '928429831821',
    projectId: 'flexshow-5c47c',
    storageBucket: 'flexshow-5c47c.appspot.com',
    iosBundleId: 'com.example.flexshow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD838Hg9nOQtoN-mgCMzSnXzJjAjA1AC5k',
    appId: '1:928429831821:web:2370bd974f17d9cb5d54c4',
    messagingSenderId: '928429831821',
    projectId: 'flexshow-5c47c',
    authDomain: 'flexshow-5c47c.firebaseapp.com',
    storageBucket: 'flexshow-5c47c.appspot.com',
    measurementId: 'G-8MDWWCQGV4',
  );
}
